/***************************************************************************//**
* File Name: cycfg_gatt_db.c
*
* Description:
* BLE device's GATT database and device configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.40.0.4702
*
********************************************************************************
* Copyright 2021 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cycfg_gatt_db.h"
#include "wiced_bt_uuid.h"
#include "wiced_bt_gatt.h"

/*************************************************************************************
* GATT server definitions
*************************************************************************************/

const uint8_t gatt_database[] = 
{
    /* Primary Service: Generic Access */
    PRIMARY_SERVICE_UUID16 (HDLS_GAP, __UUID_SERVICE_GENERIC_ACCESS),
        /* Characteristic: Device Name */
        CHARACTERISTIC_UUID16 (HDLC_GAP_DEVICE_NAME, HDLC_GAP_DEVICE_NAME_VALUE, __UUID_CHARACTERISTIC_DEVICE_NAME, GATTDB_CHAR_PROP_READ, GATTDB_PERM_READABLE),
        /* Characteristic: Appearance */
        CHARACTERISTIC_UUID16 (HDLC_GAP_APPEARANCE, HDLC_GAP_APPEARANCE_VALUE, __UUID_CHARACTERISTIC_APPEARANCE, GATTDB_CHAR_PROP_READ, GATTDB_PERM_READABLE),
        /* Characteristic: Peripheral Preferred Connection Parameters */
        CHARACTERISTIC_UUID16 (HDLC_GAP_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS, HDLC_GAP_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS_VALUE, __UUID_CHARACTERISTIC_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS, GATTDB_CHAR_PROP_READ, GATTDB_PERM_READABLE),

    /* Primary Service: Generic Attribute */
    PRIMARY_SERVICE_UUID16 (HDLS_GATT, __UUID_SERVICE_GENERIC_ATTRIBUTE),

    /* Primary Service: Device Information */
    PRIMARY_SERVICE_UUID16 (HDLS_DIS, __UUID_SERVICE_DEVICE_INFORMATION),
        /* Characteristic: Manufacturer Name String */
        CHARACTERISTIC_UUID16 (HDLC_DIS_MANUFACTURER_NAME_STRING, HDLC_DIS_MANUFACTURER_NAME_STRING_VALUE, __UUID_CHARACTERISTIC_MANUFACTURER_NAME_STRING, GATTDB_CHAR_PROP_READ, GATTDB_PERM_READABLE),
        /* Characteristic: Model Number String */
        CHARACTERISTIC_UUID16 (HDLC_DIS_MODEL_NUMBER_STRING, HDLC_DIS_MODEL_NUMBER_STRING_VALUE, __UUID_CHARACTERISTIC_MODEL_NUMBER_STRING, GATTDB_CHAR_PROP_READ, GATTDB_PERM_READABLE),
        /* Characteristic: Serial Number String */
        CHARACTERISTIC_UUID16 (HDLC_DIS_SERIAL_NUMBER_STRING, HDLC_DIS_SERIAL_NUMBER_STRING_VALUE, __UUID_CHARACTERISTIC_SERIAL_NUMBER_STRING, GATTDB_CHAR_PROP_READ, GATTDB_PERM_READABLE),
        /* Characteristic: Software Revision String */
        CHARACTERISTIC_UUID16 (HDLC_DIS_SOFTWARE_REVISION_STRING, HDLC_DIS_SOFTWARE_REVISION_STRING_VALUE, __UUID_CHARACTERISTIC_SOFTWARE_REVISION_STRING, GATTDB_CHAR_PROP_READ, GATTDB_PERM_READABLE),
        /* Characteristic: Firmware Revision String */
        CHARACTERISTIC_UUID16 (HDLC_DIS_FIRMWARE_REVISION_STRING, HDLC_DIS_FIRMWARE_REVISION_STRING_VALUE, __UUID_CHARACTERISTIC_FIRMWARE_REVISION_STRING, GATTDB_CHAR_PROP_READ, GATTDB_PERM_READABLE),
        /* Characteristic: Hardware Revision String */
        CHARACTERISTIC_UUID16 (HDLC_DIS_HARDWARE_REVISION_STRING, HDLC_DIS_HARDWARE_REVISION_STRING_VALUE, __UUID_CHARACTERISTIC_HARDWARE_REVISION_STRING, GATTDB_CHAR_PROP_READ, GATTDB_PERM_READABLE),
        /* Characteristic: PnP ID */
        CHARACTERISTIC_UUID16 (HDLC_DIS_PNP_ID, HDLC_DIS_PNP_ID_VALUE, __UUID_CHARACTERISTIC_PNP_ID, GATTDB_CHAR_PROP_READ, GATTDB_PERM_READABLE),
        /* Characteristic: System ID */
        CHARACTERISTIC_UUID16 (HDLC_DIS_SYSTEM_ID, HDLC_DIS_SYSTEM_ID_VALUE, __UUID_CHARACTERISTIC_SYSTEM_ID, GATTDB_CHAR_PROP_READ, GATTDB_PERM_READABLE),

    /* Primary Service: Human Interface Device */
    PRIMARY_SERVICE_UUID16 (HDLS_HIDS, __UUID_SERVICE_HUMAN_INTERFACE_DEVICE),
        /* Characteristic: Report Map */
        CHARACTERISTIC_UUID16 (HDLC_HIDS_REPORT_MAP, HDLC_HIDS_REPORT_MAP_VALUE, __UUID_CHARACTERISTIC_REPORT_MAP, GATTDB_CHAR_PROP_READ, GATTDB_PERM_READABLE),
            /* Descriptor: External Report Reference */
            CHAR_DESCRIPTOR_UUID16 (HDLD_HIDS_REPORT_MAP_EXTERNAL_REPORT_REFERENCE, __UUID_DESCRIPTOR_EXTERNAL_REPORT_REFERENCE, GATTDB_PERM_READABLE),
        /* Characteristic: HID Information */
        CHARACTERISTIC_UUID16 (HDLC_HIDS_HID_INFORMATION, HDLC_HIDS_HID_INFORMATION_VALUE, __UUID_CHARACTERISTIC_HID_INFORMATION, GATTDB_CHAR_PROP_READ, GATTDB_PERM_READABLE),
        /* Characteristic: HID Control Point */
        CHARACTERISTIC_UUID16_WRITABLE (HDLC_HIDS_HID_CONTROL_POINT, HDLC_HIDS_HID_CONTROL_POINT_VALUE, __UUID_CHARACTERISTIC_HID_CONTROL_POINT, GATTDB_CHAR_PROP_WRITE_NO_RESPONSE, GATTDB_PERM_WRITE_CMD),
        /* Characteristic: Report */
        CHARACTERISTIC_UUID16 (HDLC_HIDS_REPORT, HDLC_HIDS_REPORT_VALUE, __UUID_CHARACTERISTIC_REPORT, GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_NOTIFY, GATTDB_PERM_READABLE),
            /* Descriptor: Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_HIDS_REPORT_CLIENT_CHAR_CONFIG, __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ),
            /* Descriptor: Report Reference */
            CHAR_DESCRIPTOR_UUID16 (HDLD_HIDS_REPORT_REPORT_REFERENCE, __UUID_DESCRIPTOR_REPORT_REFERENCE, GATTDB_PERM_READABLE),

    /* Primary Service: Battery */
    PRIMARY_SERVICE_UUID16 (HDLS_BAS, __UUID_SERVICE_BATTERY),
        /* Characteristic: Battery Level */
        CHARACTERISTIC_UUID16 (HDLC_BAS_BATTERY_LEVEL, HDLC_BAS_BATTERY_LEVEL_VALUE, __UUID_CHARACTERISTIC_BATTERY_LEVEL, GATTDB_CHAR_PROP_READ, GATTDB_PERM_READABLE),
            /* Descriptor: Characteristic Presentation Format */
            CHAR_DESCRIPTOR_UUID16 (HDLD_BAS_BATTERY_LEVEL_CHAR_PRESENTATION_FORMAT, __UUID_DESCRIPTOR_CHARACTERISTIC_PRESENTATION_FORMAT, GATTDB_PERM_READABLE),
            /* Descriptor: Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_BAS_BATTERY_LEVEL_CLIENT_CHAR_CONFIG, __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ),

    /* Primary Service: Custom Service */
    PRIMARY_SERVICE_UUID128 (HDLS_CUSTOM_SERVICE, __UUID_SERVICE_CUSTOM_SERVICE),
        /* Characteristic: WIFI SSID */
        CHARACTERISTIC_UUID128_WRITABLE (HDLC_CUSTOM_SERVICE_WIFI_SSID, HDLC_CUSTOM_SERVICE_WIFI_SSID_VALUE, __UUID_CHARACTERISTIC_CUSTOM_SERVICE_WIFI_SSID, GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_WRITE, GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ),
            /* Descriptor: Characteristic User Description */
            CHAR_DESCRIPTOR_UUID16 (HDLD_CUSTOM_SERVICE_WIFI_SSID_CHAR_USER_DESCRIPTION, __UUID_DESCRIPTOR_CHARACTERISTIC_USER_DESCRIPTION, GATTDB_PERM_READABLE),
        /* Characteristic: WIFI PASSWORD */
        CHARACTERISTIC_UUID128_WRITABLE (HDLC_CUSTOM_SERVICE_WIFI_PASSWORD, HDLC_CUSTOM_SERVICE_WIFI_PASSWORD_VALUE, __UUID_CHARACTERISTIC_CUSTOM_SERVICE_WIFI_PASSWORD, GATTDB_CHAR_PROP_WRITE, GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE),
            /* Descriptor: Characteristic User Description */
            CHAR_DESCRIPTOR_UUID16 (HDLD_CUSTOM_SERVICE_WIFI_PASSWORD_CHAR_USER_DESCRIPTION, __UUID_DESCRIPTOR_CHARACTERISTIC_USER_DESCRIPTION, GATTDB_PERM_READABLE),
        /* Characteristic: WIFI CONNECTION */
        CHARACTERISTIC_UUID128_WRITABLE (HDLC_CUSTOM_SERVICE_WIFI_CONNECTION, HDLC_CUSTOM_SERVICE_WIFI_CONNECTION_VALUE, __UUID_CHARACTERISTIC_CUSTOM_SERVICE_WIFI_CONNECTION, GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_NOTIFY, GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ),
            /* Descriptor: Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_CUSTOM_SERVICE_WIFI_CONNECTION_CLIENT_CHAR_CONFIG, __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ),
            /* Descriptor: Characteristic User Description */
            CHAR_DESCRIPTOR_UUID16 (HDLD_CUSTOM_SERVICE_WIFI_CONNECTION_CHAR_USER_DESCRIPTION, __UUID_DESCRIPTOR_CHARACTERISTIC_USER_DESCRIPTION, GATTDB_PERM_READABLE),
			
			/* Primary Service: test service */
    PRIMARY_SERVICE_UUID16 (HDLS_TEST_SERVICE, __UUID_SERVICE_TEST_SERVICE),
        /* Characteristic: test Chara */
        CHARACTERISTIC_UUID16_WRITABLE (HDLC_TEST_SERVICE_TEST_CHARA, HDLC_TEST_SERVICE_TEST_CHARA_VALUE, __UUID_CHARACTERISTIC_TEST_SERVICE_TEST_CHARA, GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_WRITE, GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_RELIABLE_WRITE),
		
		/* Primary Service: Current Time */
    PRIMARY_SERVICE_UUID16 (HDLS_NOTIFY_SERVICE, __UUID_SERVICE_NOTIFY_SERVICE),
        /* Characteristic: Current Time */
        CHARACTERISTIC_UUID16 (HDLC_NOTIFY_SERVICE, HDLC_NOTIFY_SERVICE_VALUE, __UUID_CHARACTERISTIC_NOTIFY_SERVICE, GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_NOTIFY | GATTDB_CHAR_PROP_INDICATE, GATTDB_PERM_READABLE),
            /* Descriptor: Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_NOTIFY_SERVICE_CLIENT_CHAR_CONFIG, __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ),
};

/* Length of the GATT database */
const uint16_t gatt_database_len = sizeof(gatt_database);

/*************************************************************************************
 * GATT Initial Value Arrays
 ************************************************************************************/
 
uint8_t app_gap_device_name[]                                      = {'C', 'l', 'o', 'u', 'd', 'G', 'a', 'm', 'e', 'P', 'T', '1', '\0', };
uint8_t app_gap_appearance[]                                       = {0xC4, 0x03, };
uint8_t app_gap_peripheral_preferred_connection_parameters[]       = {0x06, 0x00, 0x1E, 0x00, 0x00, 0x00, 0xE8, 0x03, };
uint8_t app_dis_manufacturer_name_string[]                         = {'i', 'R', 'e', 'a', 'd', 'y', 'G', 'o', };
uint8_t app_dis_model_number_string[]                              = {'C', 'l', 'o', 'u', 'd', 'G', 'a', 'm', 'e', 'p', 'a', 'd', };
uint8_t app_dis_serial_number_string[]                             = {'1', '2', '3', '4', '5', '6', '7', '8', };
uint8_t app_dis_software_revision_string[]                         = {'0', '.', '1', '.', '0', };
uint8_t app_dis_firmware_revision_string[]                         = {'M', 'T', 'B', '2', '.', '3', '1', '_', 'B', 'T', '3', '.', '0', };
uint8_t app_dis_hardware_revision_string[]                         = {'0', '.', '1', };
uint8_t app_dis_pnp_id[]                                           = {0x01, 0x15, 0x19, 0x0A, 0x1A, 0x01, 0x00, };
uint8_t app_dis_system_id[]                                        = {0x7B, 0x00, 0x00, 0x00, 0x00, 0xA6, 0x02, 0x00, };
uint8_t app_hids_report_map[]                                      = {0x05, 0x01, 0x09, 0x05, 0xA1, 0x01, 0xA1, 0x00, 0x05, 0x09, 0x15, 0x00, 0x25, 0x01, 0x09, 0x01, 0x09, 0x02, 0x09, 0x04, 0x09, 0x05, 0x09, 0x07, 0x09, 0x08, 0x09, 0x0E, 0x09, 0x0F, 0x09, 0x0B, 0x09, 0x0C, 0x09, 0x0D, 0x09, 0x13, 0x09, 0x14, 0x09, 0x11, 0x09, 0x12, 0x75, 0x01, 0x95, 0x0F, 0x81, 0x02, 0x75, 0x01, 0x95, 0x01, 0x81, 0x01, 0x05, 0x01, 0x09, 0x39, 0x15, 0x00, 0x25, 0x07, 0x35, 0x00, 0x46, 0x3B, 0x01, 0x65, 0x14, 0x75, 0x04, 0x95, 0x01, 0x81, 0x42, 0x65, 0x00, 0x75, 0x01, 0x95, 0x04, 0x81, 0x01, 0x05, 0x0C, 0x0A, 0x24, 0x02, 0x05, 0x07, 0x09, 0x46, 0x05, 0x0C, 0x0A, 0x23, 0x02, 0x15, 0x00, 0x25, 0x01, 0x35, 0x00, 0x45, 0x01, 0x75, 0x01, 0x95, 0x03, 0x81, 0x02, 0x75, 0x01, 0x95, 0x05, 0x81, 0x01, 0x05, 0x01, 0x09, 0x30, 0x09, 0x31, 0x09, 0x32, 0x09, 0x35, 0x15, 0x00, 0x27, 0x28, 0xFF, 0x00, 0x00, 0x35, 0x00, 0x47, 0x28, 0xFF, 0x00, 0x00, 0x75, 0x10, 0x95, 0x04, 0x81, 0x02, 0x05, 0x02, 0x15, 0x00, 0x26, 0xFF, 0x00, 0x09, 0xC5, 0x09, 0xC4, 0x95, 0x02, 0x75, 0x08, 0x81, 0x02, 0xC0, 0xC0, };
uint8_t app_hids_report_map_external_report_reference[]            = {0x00, 0x00, };
uint8_t app_hids_hid_information[]                                 = {0x00, 0x00, 0x00, 0x00, };
uint8_t app_hids_hid_control_point[]                               = {0x00, };
uint8_t app_hids_report[]                                          = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, };
uint8_t app_hids_report_client_char_config[]                       = {0x00, 0x00, };
uint8_t app_hids_report_report_reference[]                         = {0x00, 0x01, };
uint8_t app_bas_battery_level[]                                    = {0x58, };
uint8_t app_bas_battery_level_char_presentation_format[]           = {0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, };
uint8_t app_bas_battery_level_client_char_config[]                 = {0x00, 0x00, };
uint8_t app_custom_service_wifi_ssid[]                             = {'\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', };
uint8_t app_custom_service_wifi_ssid_char_user_description[]       = {'W', 'i', 'F', 'i', ' ', 'S', 'S', 'I', 'D', };
uint8_t app_custom_service_wifi_password[]                         = {'\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', };
uint8_t app_custom_service_wifi_password_char_user_description[]   = {'W', 'i', 'F', 'i', ' ', 'P', 'a', 's', 's', 'w', 'o', 'r', 'd', };
uint8_t app_custom_service_wifi_connection[]                       = {0x00, };
uint8_t app_custom_service_wifi_connection_client_char_config[]    = {0x00, 0x00, };
uint8_t app_custom_service_wifi_connection_char_user_description[] = {'W', 'i', 'F', 'i', ' ', 'C', 'o', 'n', 'n', 'e', 'c', 't', 'i', 'o', 'n', ' ', 'C', 'o', 'n', 't', 'r', 'o', 'l', };
uint8_t app_test_service_test_chara[]             = {'2', '3', '4', '2', '3', '5', '3', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', };
uint8_t app_notify_service_chara[]                    = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,0x00, 0x00, 0x00,};
uint8_t app_notify_service_client_char_config[] = {0x00, 0x00, };
 
 /************************************************************************************
 * GATT Lookup Table
 ************************************************************************************/
 
gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[] =
{
    /* { attribute handle,                                       maxlen, curlen, attribute data } */
    { HDLC_GAP_DEVICE_NAME_VALUE,                                12,     12,     app_gap_device_name },
    { HDLC_GAP_APPEARANCE_VALUE,                                 2,      2,      app_gap_appearance },
    { HDLC_GAP_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS_VALUE, 8,      8,      app_gap_peripheral_preferred_connection_parameters },
    { HDLC_DIS_MANUFACTURER_NAME_STRING_VALUE,                   8,      8,      app_dis_manufacturer_name_string },
    { HDLC_DIS_MODEL_NUMBER_STRING_VALUE,                        12,     12,     app_dis_model_number_string },
    { HDLC_DIS_SERIAL_NUMBER_STRING_VALUE,                       8,      8,      app_dis_serial_number_string },
    { HDLC_DIS_SOFTWARE_REVISION_STRING_VALUE,                   5,      5,      app_dis_software_revision_string },
    { HDLC_DIS_FIRMWARE_REVISION_STRING_VALUE,                   13,     13,     app_dis_firmware_revision_string },
    { HDLC_DIS_HARDWARE_REVISION_STRING_VALUE,                   3,      3,      app_dis_hardware_revision_string },
    { HDLC_DIS_PNP_ID_VALUE,                                     7,      7,      app_dis_pnp_id },
    { HDLC_DIS_SYSTEM_ID_VALUE,                                  8,      8,      app_dis_system_id },
    { HDLC_HIDS_REPORT_MAP_VALUE,                                168,    168,    app_hids_report_map },
    { HDLD_HIDS_REPORT_MAP_EXTERNAL_REPORT_REFERENCE,            2,      2,      app_hids_report_map_external_report_reference },
    { HDLC_HIDS_HID_INFORMATION_VALUE,                           4,      4,      app_hids_hid_information },
    { HDLC_HIDS_HID_CONTROL_POINT_VALUE,                         1,      1,      app_hids_hid_control_point },
    { HDLC_HIDS_REPORT_VALUE,                                    14,     14,     app_hids_report },
    { HDLD_HIDS_REPORT_CLIENT_CHAR_CONFIG,                       2,      2,      app_hids_report_client_char_config },
    { HDLD_HIDS_REPORT_REPORT_REFERENCE,                         2,      2,      app_hids_report_report_reference },
    { HDLC_BAS_BATTERY_LEVEL_VALUE,                              1,      1,      app_bas_battery_level },
    { HDLD_BAS_BATTERY_LEVEL_CHAR_PRESENTATION_FORMAT,           7,      7,      app_bas_battery_level_char_presentation_format },
    { HDLD_BAS_BATTERY_LEVEL_CLIENT_CHAR_CONFIG,                 2,      2,      app_bas_battery_level_client_char_config },
    { HDLC_CUSTOM_SERVICE_WIFI_SSID_VALUE,                       32,     32,     app_custom_service_wifi_ssid },
    { HDLD_CUSTOM_SERVICE_WIFI_SSID_CHAR_USER_DESCRIPTION,       9,      9,      app_custom_service_wifi_ssid_char_user_description },
    { HDLC_CUSTOM_SERVICE_WIFI_PASSWORD_VALUE,                   63,     63,     app_custom_service_wifi_password },
    { HDLD_CUSTOM_SERVICE_WIFI_PASSWORD_CHAR_USER_DESCRIPTION,   13,     13,     app_custom_service_wifi_password_char_user_description },
    { HDLC_CUSTOM_SERVICE_WIFI_CONNECTION_VALUE,                 1,      1,      app_custom_service_wifi_connection },
    { HDLD_CUSTOM_SERVICE_WIFI_CONNECTION_CLIENT_CHAR_CONFIG,    2,      2,      app_custom_service_wifi_connection_client_char_config },
    { HDLD_CUSTOM_SERVICE_WIFI_CONNECTION_CHAR_USER_DESCRIPTION, 23,     23,     app_custom_service_wifi_connection_char_user_description },
	{ HDLC_TEST_SERVICE_TEST_CHARA_VALUE,       64,     64,     app_test_service_test_chara },
	{ HDLC_NOTIFY_SERVICE_VALUE,              15,     15,     app_notify_service_chara },
    { HDLD_NOTIFY_SERVICE_CLIENT_CHAR_CONFIG, 2,      2,      app_notify_service_client_char_config },
};

/* Number of Lookup Table entries */
const uint16_t app_gatt_db_ext_attr_tbl_size = (sizeof(app_gatt_db_ext_attr_tbl) / sizeof(gatt_db_lookup_table_t));

/* Number of GATT initial value arrays entries */
const uint16_t app_gap_device_name_len = 12;
const uint16_t app_gap_appearance_len = (sizeof(app_gap_appearance));
const uint16_t app_gap_peripheral_preferred_connection_parameters_len = (sizeof(app_gap_peripheral_preferred_connection_parameters));
const uint16_t app_dis_manufacturer_name_string_len = (sizeof(app_dis_manufacturer_name_string));
const uint16_t app_dis_model_number_string_len = (sizeof(app_dis_model_number_string));
const uint16_t app_dis_serial_number_string_len = (sizeof(app_dis_serial_number_string));
const uint16_t app_dis_software_revision_string_len = (sizeof(app_dis_software_revision_string));
const uint16_t app_dis_firmware_revision_string_len = (sizeof(app_dis_firmware_revision_string));
const uint16_t app_dis_hardware_revision_string_len = (sizeof(app_dis_hardware_revision_string));
const uint16_t app_dis_pnp_id_len = (sizeof(app_dis_pnp_id));
const uint16_t app_dis_system_id_len = (sizeof(app_dis_system_id));
const uint16_t app_hids_report_map_len = (sizeof(app_hids_report_map));
const uint16_t app_hids_report_map_external_report_reference_len = (sizeof(app_hids_report_map_external_report_reference));
const uint16_t app_hids_hid_information_len = (sizeof(app_hids_hid_information));
const uint16_t app_hids_hid_control_point_len = (sizeof(app_hids_hid_control_point));
const uint16_t app_hids_report_len = (sizeof(app_hids_report));
const uint16_t app_hids_report_client_char_config_len = (sizeof(app_hids_report_client_char_config));
const uint16_t app_hids_report_report_reference_len = (sizeof(app_hids_report_report_reference));
const uint16_t app_bas_battery_level_len = (sizeof(app_bas_battery_level));
const uint16_t app_bas_battery_level_char_presentation_format_len = (sizeof(app_bas_battery_level_char_presentation_format));
const uint16_t app_bas_battery_level_client_char_config_len = (sizeof(app_bas_battery_level_client_char_config));
const uint16_t app_custom_service_wifi_ssid_len = (sizeof(app_custom_service_wifi_ssid));
const uint16_t app_custom_service_wifi_ssid_char_user_description_len = (sizeof(app_custom_service_wifi_ssid_char_user_description));
const uint16_t app_custom_service_wifi_password_len = (sizeof(app_custom_service_wifi_password));
const uint16_t app_custom_service_wifi_password_char_user_description_len = (sizeof(app_custom_service_wifi_password_char_user_description));
const uint16_t app_custom_service_wifi_connection_len = (sizeof(app_custom_service_wifi_connection));
const uint16_t app_custom_service_wifi_connection_client_char_config_len = (sizeof(app_custom_service_wifi_connection_client_char_config));
const uint16_t app_custom_service_wifi_connection_char_user_description_len = (sizeof(app_custom_service_wifi_connection_char_user_description));
const uint16_t app_test_service_test_chara_len = (sizeof(app_test_service_test_chara));
const uint16_t app_notify_service_chara_len = (sizeof(app_notify_service_chara));
const uint16_t app_notify_service_client_char_config_len = (sizeof(app_notify_service_client_char_config));

