/***************************************************************************//**
* File Name: cycfg_gatt_db.h
*
* Description:
* Definitions for constants used in the device's GATT database and function
* prototypes.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.40.0.4702
*
********************************************************************************
* Copyright 2021 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_GATT_DB_H)
#define CYCFG_GATT_DB_H

#include "stdint.h"

#define __UUID_SERVICE_GENERIC_ACCESS                                0x1800
#define __UUID_CHARACTERISTIC_DEVICE_NAME                            0x2A00
#define __UUID_CHARACTERISTIC_APPEARANCE                             0x2A01
#define __UUID_CHARACTERISTIC_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS    0x2A04
#define __UUID_SERVICE_GENERIC_ATTRIBUTE                             0x1801
#define __UUID_SERVICE_DEVICE_INFORMATION                            0x180A
#define __UUID_CHARACTERISTIC_MANUFACTURER_NAME_STRING               0x2A29
#define __UUID_CHARACTERISTIC_MODEL_NUMBER_STRING                    0x2A24
#define __UUID_CHARACTERISTIC_SERIAL_NUMBER_STRING                   0x2A25
#define __UUID_CHARACTERISTIC_SOFTWARE_REVISION_STRING               0x2A28
#define __UUID_CHARACTERISTIC_FIRMWARE_REVISION_STRING               0x2A26
#define __UUID_CHARACTERISTIC_HARDWARE_REVISION_STRING               0x2A27
#define __UUID_CHARACTERISTIC_PNP_ID                                 0x2A50
#define __UUID_CHARACTERISTIC_SYSTEM_ID                              0x2A23
#define __UUID_SERVICE_HUMAN_INTERFACE_DEVICE                        0x1812
#define __UUID_CHARACTERISTIC_REPORT_MAP                             0x2A4B
#define __UUID_DESCRIPTOR_EXTERNAL_REPORT_REFERENCE                  0x2907
#define __UUID_CHARACTERISTIC_HID_INFORMATION                        0x2A4A
#define __UUID_CHARACTERISTIC_HID_CONTROL_POINT                      0x2A4C
#define __UUID_CHARACTERISTIC_REPORT                                 0x2A4D
#define __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION        0x2902
#define __UUID_DESCRIPTOR_REPORT_REFERENCE                           0x2908
#define __UUID_SERVICE_BATTERY                                       0x180F
#define __UUID_CHARACTERISTIC_BATTERY_LEVEL                          0x2A19
#define __UUID_DESCRIPTOR_CHARACTERISTIC_PRESENTATION_FORMAT         0x2904
#define __UUID_SERVICE_CUSTOM_SERVICE                                0x5B, 0x19, 0xBA, 0xE4, 0xE4, 0x52, 0xA9, 0x96, 0xF1, 0x4A, 0x84, 0xC8, 0x09, 0x4D, 0xC0, 0x21
#define __UUID_CHARACTERISTIC_CUSTOM_SERVICE_WIFI_SSID               0x63, 0x97, 0xCA, 0x92, 0x5F, 0x02, 0x1E, 0xB9, 0x3D, 0x4A, 0x31, 0x6B, 0x43, 0x00, 0x50, 0x1E
#define __UUID_DESCRIPTOR_CHARACTERISTIC_USER_DESCRIPTION            0x2901
#define __UUID_CHARACTERISTIC_CUSTOM_SERVICE_WIFI_PASSWORD           0x64, 0x97, 0xCA, 0x92, 0x5F, 0x02, 0x1E, 0xB9, 0x3D, 0x4A, 0x31, 0x6B, 0x43, 0x00, 0x50, 0x1E
#define __UUID_CHARACTERISTIC_CUSTOM_SERVICE_WIFI_CONNECTION         0x65, 0x97, 0xCA, 0x92, 0x5F, 0x02, 0x1E, 0xB9, 0x3D, 0x4A, 0x31, 0x6B, 0x43, 0x00, 0x50, 0x1E

#define __UUID_SERVICE_TEST_SERVICE                 0xFF00
#define __UUID_CHARACTERISTIC_TEST_SERVICE_TEST_CHARA    0xFF01

#define __UUID_SERVICE_NOTIFY_SERVICE                 0xFF02
#define __UUID_CHARACTERISTIC_NOTIFY_SERVICE    0xFF03
#define __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION    0xFF04

/* Service Generic Access */
#define HDLS_GAP                                                     0x01
/* Characteristic Device Name */
#define HDLC_GAP_DEVICE_NAME                                         0x02
#define HDLC_GAP_DEVICE_NAME_VALUE                                   0x03
/* Characteristic Appearance */
#define HDLC_GAP_APPEARANCE                                          0x04
#define HDLC_GAP_APPEARANCE_VALUE                                    0x05
/* Characteristic Peripheral Preferred Connection Parameters */
#define HDLC_GAP_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS          0x06
#define HDLC_GAP_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS_VALUE    0x07

/* Service Generic Attribute */
#define HDLS_GATT                                                    0x08

/* Service Device Information */
#define HDLS_DIS                                                     0x09
/* Characteristic Manufacturer Name String */
#define HDLC_DIS_MANUFACTURER_NAME_STRING                            0x0A
#define HDLC_DIS_MANUFACTURER_NAME_STRING_VALUE                      0x0B
/* Characteristic Model Number String */
#define HDLC_DIS_MODEL_NUMBER_STRING                                 0x0C
#define HDLC_DIS_MODEL_NUMBER_STRING_VALUE                           0x0D
/* Characteristic Serial Number String */
#define HDLC_DIS_SERIAL_NUMBER_STRING                                0x0E
#define HDLC_DIS_SERIAL_NUMBER_STRING_VALUE                          0x0F
/* Characteristic Software Revision String */
#define HDLC_DIS_SOFTWARE_REVISION_STRING                            0x10
#define HDLC_DIS_SOFTWARE_REVISION_STRING_VALUE                      0x11
/* Characteristic Firmware Revision String */
#define HDLC_DIS_FIRMWARE_REVISION_STRING                            0x12
#define HDLC_DIS_FIRMWARE_REVISION_STRING_VALUE                      0x13
/* Characteristic Hardware Revision String */
#define HDLC_DIS_HARDWARE_REVISION_STRING                            0x14
#define HDLC_DIS_HARDWARE_REVISION_STRING_VALUE                      0x15
/* Characteristic PnP ID */
#define HDLC_DIS_PNP_ID                                              0x16
#define HDLC_DIS_PNP_ID_VALUE                                        0x17
/* Characteristic System ID */
#define HDLC_DIS_SYSTEM_ID                                           0x18
#define HDLC_DIS_SYSTEM_ID_VALUE                                     0x19

/* Service Human Interface Device */
#define HDLS_HIDS                                                    0x1A
/* Characteristic Report Map */
#define HDLC_HIDS_REPORT_MAP                                         0x1B
#define HDLC_HIDS_REPORT_MAP_VALUE                                   0x1C
/* Descriptor External Report Reference */
#define HDLD_HIDS_REPORT_MAP_EXTERNAL_REPORT_REFERENCE               0x1D
/* Characteristic HID Information */
#define HDLC_HIDS_HID_INFORMATION                                    0x1E
#define HDLC_HIDS_HID_INFORMATION_VALUE                              0x1F
/* Characteristic HID Control Point */
#define HDLC_HIDS_HID_CONTROL_POINT                                  0x20
#define HDLC_HIDS_HID_CONTROL_POINT_VALUE                            0x21
/* Characteristic Report */
#define HDLC_HIDS_REPORT                                             0x22
#define HDLC_HIDS_REPORT_VALUE                                       0x23
/* Descriptor Client Characteristic Configuration */
#define HDLD_HIDS_REPORT_CLIENT_CHAR_CONFIG                          0x24
/* Descriptor Report Reference */
#define HDLD_HIDS_REPORT_REPORT_REFERENCE                            0x25

/* Service Battery */
#define HDLS_BAS                                                     0x26
/* Characteristic Battery Level */
#define HDLC_BAS_BATTERY_LEVEL                                       0x27
#define HDLC_BAS_BATTERY_LEVEL_VALUE                                 0x28
/* Descriptor Characteristic Presentation Format */
#define HDLD_BAS_BATTERY_LEVEL_CHAR_PRESENTATION_FORMAT              0x29
/* Descriptor Client Characteristic Configuration */
#define HDLD_BAS_BATTERY_LEVEL_CLIENT_CHAR_CONFIG                    0x2A

/* Service Custom Service */
#define HDLS_CUSTOM_SERVICE                                          0x2B
/* Characteristic WIFI SSID */
#define HDLC_CUSTOM_SERVICE_WIFI_SSID                                0x2C
#define HDLC_CUSTOM_SERVICE_WIFI_SSID_VALUE                          0x2D
/* Descriptor Characteristic User Description */
#define HDLD_CUSTOM_SERVICE_WIFI_SSID_CHAR_USER_DESCRIPTION          0x2E
/* Characteristic WIFI PASSWORD */
#define HDLC_CUSTOM_SERVICE_WIFI_PASSWORD                            0x2F
#define HDLC_CUSTOM_SERVICE_WIFI_PASSWORD_VALUE                      0x30
/* Descriptor Characteristic User Description */
#define HDLD_CUSTOM_SERVICE_WIFI_PASSWORD_CHAR_USER_DESCRIPTION      0x31
/* Characteristic WIFI CONNECTION */
#define HDLC_CUSTOM_SERVICE_WIFI_CONNECTION                          0x32
#define HDLC_CUSTOM_SERVICE_WIFI_CONNECTION_VALUE                    0x33
/* Descriptor Client Characteristic Configuration */
#define HDLD_CUSTOM_SERVICE_WIFI_CONNECTION_CLIENT_CHAR_CONFIG       0x34
/* Descriptor Characteristic User Description */
#define HDLD_CUSTOM_SERVICE_WIFI_CONNECTION_CHAR_USER_DESCRIPTION    0x35

/* Service test service */
#define HDLS_TEST_SERVICE                           0x36
/* Characteristic test Chara */
#define HDLC_TEST_SERVICE_TEST_CHARA                0x37
#define HDLC_TEST_SERVICE_TEST_CHARA_VALUE          0x38

/* Service test service */
#define HDLS_NOTIFY_SERVICE                           0x40
/* Characteristic test Chara */
#define HDLC_NOTIFY_SERVICE                0x41
#define HDLC_NOTIFY_SERVICE_VALUE          0x42
#define HDLD_NOTIFY_SERVICE_CLIENT_CHAR_CONFIG          0x43

/* External Lookup Table Entry */
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table_t;

/* External definitions */
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[];
extern const uint16_t app_gatt_db_ext_attr_tbl_size;
extern uint8_t app_gap_device_name[];
extern const uint16_t app_gap_device_name_len;
extern uint8_t app_gap_appearance[];
extern const uint16_t app_gap_appearance_len;
extern uint8_t app_gap_peripheral_preferred_connection_parameters[];
extern const uint16_t app_gap_peripheral_preferred_connection_parameters_len;
extern uint8_t app_dis_manufacturer_name_string[];
extern const uint16_t app_dis_manufacturer_name_string_len;
extern uint8_t app_dis_model_number_string[];
extern const uint16_t app_dis_model_number_string_len;
extern uint8_t app_dis_serial_number_string[];
extern const uint16_t app_dis_serial_number_string_len;
extern uint8_t app_dis_software_revision_string[];
extern const uint16_t app_dis_software_revision_string_len;
extern uint8_t app_dis_firmware_revision_string[];
extern const uint16_t app_dis_firmware_revision_string_len;
extern uint8_t app_dis_hardware_revision_string[];
extern const uint16_t app_dis_hardware_revision_string_len;
extern uint8_t app_dis_pnp_id[];
extern const uint16_t app_dis_pnp_id_len;
extern uint8_t app_dis_system_id[];
extern const uint16_t app_dis_system_id_len;
extern uint8_t app_hids_report_map[];
extern const uint16_t app_hids_report_map_len;
extern uint8_t app_hids_report_map_external_report_reference[];
extern const uint16_t app_hids_report_map_external_report_reference_len;
extern uint8_t app_hids_hid_information[];
extern const uint16_t app_hids_hid_information_len;
extern uint8_t app_hids_hid_control_point[];
extern const uint16_t app_hids_hid_control_point_len;
extern uint8_t app_hids_report[];
extern const uint16_t app_hids_report_len;
extern uint8_t app_hids_report_client_char_config[];
extern const uint16_t app_hids_report_client_char_config_len;
extern uint8_t app_hids_report_report_reference[];
extern const uint16_t app_hids_report_report_reference_len;
extern uint8_t app_bas_battery_level[];
extern const uint16_t app_bas_battery_level_len;
extern uint8_t app_bas_battery_level_char_presentation_format[];
extern const uint16_t app_bas_battery_level_char_presentation_format_len;
extern uint8_t app_bas_battery_level_client_char_config[];
extern const uint16_t app_bas_battery_level_client_char_config_len;
extern uint8_t app_custom_service_wifi_ssid[];
extern const uint16_t app_custom_service_wifi_ssid_len;
extern uint8_t app_custom_service_wifi_ssid_char_user_description[];
extern const uint16_t app_custom_service_wifi_ssid_char_user_description_len;
extern uint8_t app_custom_service_wifi_password[];
extern const uint16_t app_custom_service_wifi_password_len;
extern uint8_t app_custom_service_wifi_password_char_user_description[];
extern const uint16_t app_custom_service_wifi_password_char_user_description_len;
extern uint8_t app_custom_service_wifi_connection[];
extern const uint16_t app_custom_service_wifi_connection_len;
extern uint8_t app_custom_service_wifi_connection_client_char_config[];
extern const uint16_t app_custom_service_wifi_connection_client_char_config_len;
extern uint8_t app_custom_service_wifi_connection_char_user_description[];
extern const uint16_t app_custom_service_wifi_connection_char_user_description_len;
extern uint8_t app_test_service_test_chara[];
extern const uint16_t app_test_service_test_chara_len;
extern uint8_t app_notify_service_chara[];
extern const uint16_t app_notify_service_chara_len;
extern uint8_t app_notify_service_client_char_config[];
extern const uint16_t app_notify_service_client_char_config_len;

#endif /* CYCFG_GATT_DB_H */

