/***************************************************************************//**
* File Name: cycfg_gap.c
*
* Description:
* BLE device's GAP configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.40.0.4702
*
********************************************************************************
* Copyright 2021 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cycfg_gap.h"

/* Device address */
const wiced_bt_device_address_t cy_bt_device_address = {0xCC, 0x43, 0x01, 0x12, 0x45, 0xC0};

const uint8_t cy_bt_adv_packet_elem_0[1] = { 0x06 };
const uint8_t cy_bt_adv_packet_elem_1[12] = { 0x43, 0x6C, 0x6F, 0x75, 0x64, 0x47, 0x61, 0x6D, 0x65, 0x50, 0x54, 0x31 };
const uint8_t cy_bt_adv_packet_elem_2[2] = { 0x12, 0x18 };
const uint8_t cy_bt_adv_packet_elem_3[2] = { 0xC4, 0x03 };
wiced_bt_ble_advert_elem_t cy_bt_adv_packet_data[] = 
{
    /* Flags */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_FLAG, 
        .len = 1, 
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_0, 
    },
    /* Complete local name */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_NAME_COMPLETE, 
        .len = 12, 
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_1, 
    },
    /* Incomplete list of 16-bit UUIDs available */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_16SRV_PARTIAL, 
        .len = 2, 
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_2, 
    },
    /* Appearance */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_APPEARANCE, 
        .len = 2, 
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_3, 
    },
};
const uint8_t cy_bt_scan_resp_packet_elem_0[12] = { 0x43, 0x6C, 0x6F, 0x75, 0x64, 0x47, 0x61, 0x6D, 0x65, 0x50, 0x54, 0x31 };
wiced_bt_ble_advert_elem_t cy_bt_scan_resp_packet_data[] = 
{
    /* Complete local name */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_NAME_COMPLETE, 
        .len = 12, 
        .p_data = (uint8_t*)cy_bt_scan_resp_packet_elem_0, 
    },
};

